-- AlterTable
ALTER TABLE "DerivateCripto" ALTER COLUMN "price_percentage_change_24h" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "basis" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "spread" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "funding_rate" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "open_interest" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "volume_24h" SET DATA TYPE DOUBLE PRECISION;
