import type { Metadata } from "next";
import { Raleway } from "next/font/google";
import { NavBar } from "@/components/navbar";
import "./globals.css";

const inter = Raleway({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-blue-950 text-white w-screen `}>
        <div className="relative snap-y md:snap-mandatory  w-screen h-screen overflow-y-auto overflow-x-hidden  scroll-smooth ">
          <NavBar primary={false} size="medium" />
          {children}
        </div>
      </body>
    </html>
  );
}
