import type { Metadata } from "next";
import { Raleway } from "next/font/google";
import { NavBar } from "@/components/navbar";
import "./globals.css";
import { Suspense } from "react";
import Loading from "./loading";

const inter = Raleway({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-blue-950 text-white`}>
        <NavBar primary={true} size="medium" />
        <Suspense fallback={<Loading />}>{children}</Suspense>
      </body>
    </html>
  );
}
